spring.application.name=the-java-bank

spring.datasource.url = jdbc:mysql://localhost:3306/java_bank
spring.datasource.username = root
spring.datasource.password = root
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update


spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = mailid@gmail.com
spring.mail.password = epwhxhpchvdqlrpx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable = true

app.jwt.secret=Qk5aV3F4ZzZLZ2hXb1pVb1h4dFZxM2dYb2t4Rk9nWnZyY1dLQnZ2Y1Z5a1J6cA==
app.jwt.expiration=3600000